#!/bin/sh

# Gets your public ip address checks which country you are in and
# displays that information in the statusbar

# get json with info
json=$( curl "ifconfig.co/json" 2>/dev/null)  || exit
#echo ${json}
# get isp infos and clean up
isp="$( sed 's/.*hostname\":\"//' <<< ${json}  | sed 's/\",\".*//' )"
isp="${isp#*.}"
# get country
country="$( sed 's/.*country\":\"//' <<< ${json}  | sed 's/\",\".*//' )"
city="$( sed 's/.*city\":\"//' <<< ${json}  | sed 's/\",\".*//' )"

flag="$(grep "flag: " ~/.config/emoji | grep "${country}" | sed 's/;.*//' | awk '{print $1}' )"
echo "${flag} > ${city} > ${isp#*.}"
